[package]
name = "nextgallery"
version = "0.1.0"
authors = ["Alexander Lindberg <alexanderlndbrg@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = "0.4.5"
juniper = "0.14"
juniper_rocket = "0.5"
