port = 5000
name = "My Motiv Library"
cache_path = ".thumbs"
worker_threads = 6
webapp_path = "../frontend/build"

[[media]]
#TODO: fix some proper "default" which can be used to run tests in the CLooUuud
path = "/home/alexander/cloud/Backgrounds"

[database]
url = "postgres://postgres:mysecretpassword@localhost:5432/postgres"
